build:
	javac ./skel/*.java
build0:
	java -classpath ./skel Tema2 4 tests/in/test0.txt tests/out/test0_out.txt
build1:
	java -classpath ./skel Tema2 1 tests/in/test1.txt tests/out/test1_out.txt
build2:
	java -classpath ./skel Tema2 3 tests/in/test2.txt tests/out/test2_out.txt
build3:
	java -classpath ./skel Tema2 3 tests/in/test3.txt tests/out/test3_out.txt
build4:
	java -classpath ./skel Tema2 3 tests/in/test4.txt tests/out/test4_out.txt
clean:
	rm *.class